name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "helm/migration-app/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name acrmigrationlab

      - name: Build Docker image
        run: |
          docker build \
            -t acrmigrationlab.azurecr.io/migration-app:${{ github.sha }} \
            ./app

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: acrmigrationlab.azurecr.io/migration-app:${{ github.sha }}
          severity: "CRITICAL,HIGH"
          exit-code: "1"
          ignore-unfixed: true

      - name: Push Docker image
        run: |
          docker push \
            acrmigrationlab.azurecr.io/migration-app:${{ github.sha }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group rg-migration-lab \
            --name aks-migration-lab \
            --overwrite-existing

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Deploy with Helm
        run: |
          helm upgrade --install migration-app-prod ./helm/migration-app \
            --namespace prod \
            -f ./helm/migration-app/values-prod.yaml \
            --set image.repository=acrmigrationlab.azurecr.io/migration-app \
            --set image.tag=${{ github.sha }}
